language: java
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11
script:
  - mvn clean install

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      if: tag IS present
      script: 'cp .ci-settings.xml $HOME/.m2/settings.xml && mvn clean deploy -DskipTests'

