/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easyconfig.jooq.db;


import fi.jubic.easyconfig.jooq.db.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public static final User USER = fi.jubic.easyconfig.jooq.db.tables.User.USER;
}
