/*
 * This file is generated by jOOQ.
 */
package fi.jubic.easyconfig.jooq.db;


import fi.jubic.easyconfig.jooq.db.tables.User;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public static final User USER = User.USER;
}
